### ISSUE TITLE
Swift 3.1 does not work in Xcode 9

### ISSUE THREAD

**Issue by skyguy99** [tinypass/piano-sdk-for-ios#1]
The latest commit is compiled in Swift 3.1 and must be Swift 3.2 or higher to work with Xcode 9 or any subsequent versions of Xcode. As is, it causes the project to crash when opened in Xcode 9. See attached error - 
<img width="1418" alt="screen shot 2017-09-04 at 12 13 44 pm" src="https://user-images.githubusercontent.com/16522243/30033986-972760f4-916c-11e7-9065-0258268907ab.png">

**Comment by ampirator** [comment]
Added supporting of xcode 9 after public release
