### ISSUE TITLE
PianoComposer won't work with newest XCode

### ISSUE THREAD

**Issue by bdeemerInq** [tinypass/piano-sdk-for-ios#13]
When trying to run my project that includes PianoComposer with Xcode 11.4 I receive the following error:

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: Pods/PianoComposer/Frameworks/PianoComposer.framework/Modules/PianoComposer.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

You need to update the library ASAP

**Comment by ebachour** [comment]
Same problem here, please update the library. Tks

**Comment by ampirator** [comment]
Binaries can be downloaded here  https://github.com/tinypass/piano-sdk-for-ios/releases/tag/2.3.7.1
