### ISSUE TITLE
Xcode 11.5 Cannot compile with PianoComposer

### ISSUE THREAD

**Issue by bdeemerInq** [tinypass/piano-sdk-for-ios#14]
Currently receiving this error when trying to compile:

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler

**Comment by bdeemerInq** [comment]
Any update on this? I can't compile my app. Please fix this ASAP

**Comment by ampirator** [comment]
@bdeemerInq a new version (2.3.8) of SDK  was released
