### ISSUE TITLE
Swift 5.0

### ISSUE THREAD

**Issue by fermoya** [tinypass/piano-sdk-for-ios#5]
Hi,

With the new Swift 5.0, Piano doesn't seem to compile any more since it's compiled for Swift 4.2. This is an inconvenience as projects should be migrated to the new syntax and Piano is preventing me from doing so. While other frameworks let me inspect their code and even unlock the pod and change the code myself to the new syntax, this isn't possible with Piano as the pod just contains a compiled framework.

Is there a new version compatible with Swift 5.0 on the way?

Fernando.

**Comment by ampirator** [comment]
Hi, we are planning to open our sour code, in further, but for now i've made release for supporting new Xcode and swift 5.0
